; BratanVPN Windows installer (Inno Setup 6)
; Installs Flutter release build into Program Files + Start Menu / Desktop shortcuts.
;
; Build with: .\build_installer.ps1
; Or manually after flutter build windows --release:
;   ISCC.exe bratanvpn.iss

#define MyAppName "BratanVPN"
#define MyAppVersion "1.0.2"
#define MyAppPublisher "BratanVPN"
#define MyAppExeName "BratanVPN.exe"
#define MyAppIconName "bratanvpn.ico"
; Relative to this .iss file
#define ReleaseDir "..\..\build\windows\x64\runner\Release"
; Multi-size .ico next to this script (generated by _make_brand_assets.py)
#define SetupIcon "setup_icon.ico"

[Setup]
AppId={{A7E3C2B1-9F40-4D6E-8A12-B8A7A1C0D001}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DisableDirPage=yes
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
AllowNoIcons=yes
; Keep output next to installer sources
OutputDir=output
OutputBaseFilename=BratanVPN-Setup-{#MyAppVersion}
SetupIconFile={#SetupIcon}
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
; Separate .ico path — avoids Windows caching the old Flutter exe icon
UninstallDisplayIcon={app}\{#MyAppIconName}
CloseApplications=yes
RestartApplications=no
MinVersion=10.0
ShowLanguageDialog=no

[Languages]
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkedonce

[Files]
; Rename client.exe → BratanVPN.exe for a normal Program Files layout
Source: "{#ReleaseDir}\client.exe"; DestDir: "{app}"; DestName: "{#MyAppExeName}"; Flags: ignoreversion
Source: "{#ReleaseDir}\bratanvpn_helper.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseDir}\*.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ReleaseDir}\data\*"; DestDir: "{app}\data"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#ReleaseDir}\amneziawg\*"; DestDir: "{app}\amneziawg"; Flags: ignoreversion recursesubdirs createallsubdirs
; Dedicated icon file for shortcuts / uninstall / explorer (not only embedded in exe)
Source: "{#SetupIcon}"; DestDir: "{app}"; DestName: "{#MyAppIconName}"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"; IconFilename: "{app}\{#MyAppIconName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"; IconFilename: "{app}\{#MyAppIconName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[UninstallRun]
; Remove helper Windows service (tunnel) before deleting files.
Filename: "{app}\bratanvpn_helper.exe"; Parameters: "uninstall"; RunOnceId: "BratanVpnHelperUninstall"; Flags: runhidden waituntilterminated
