"""add vpn clients table

Revision ID: 17a448b79be1
Revises: 7b25f5a14fc7
Create Date: 2026-07-18 03:54:37.788307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17a448b79be1'
down_revision: Union[str, Sequence[str], None] = '7b25f5a14fc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vpn_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_key_id', sa.Integer(), nullable=False),
    sa.Column('public_key', sa.String(length=255), nullable=False),
    sa.Column('vpn_ip', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['access_key_id'], ['access_keys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_key_id'),
    sa.UniqueConstraint('public_key'),
    sa.UniqueConstraint('vpn_ip')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vpn_clients')
    # ### end Alembic commands ###
